# Generated by Django 4.2.1 on 2023-05-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecasts", "0002_remove_models_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="uploads/")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
