# Generated by Django 4.2.1 on 2023-05-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecasts", "0004_alter_fileimport_csv_file_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileImport",
        ),
    ]
