# Generated by Django 3.1.7 on 2021-04-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name_plural': 'Акции и предложения',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ФИО')),
                ('time_from', models.TextField(verbose_name='Время от начала бронирования')),
                ('time_to', models.TextField(verbose_name='время до конца бронирования')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('number_of_table', models.IntegerField(verbose_name='Номер столика')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время на момент бронирования')),
            ],
            options={
                'verbose_name_plural': 'Забронировать столик',
                'ordering': ['created', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Категории блюд',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ФИО')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Время отправки сообщения')),
            ],
            options={
                'verbose_name_plural': 'Чат с администратором',
                'ordering': ['created', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('name', models.CharField(max_length=100, verbose_name='Название ресторана (одно и то же)')),
            ],
            options={
                'verbose_name_plural': 'Главная страница - тайтлы в меню',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('message', models.TextField(verbose_name='Текст отзыва')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания отзыва')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Добавьте аватар')),
                ('profiles', models.ManyToManyField(to='main.Profile')),
            ],
            options={
                'verbose_name_plural': 'Отзывы посетителей',
                'ordering': ['created', 'title_fio'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название блюда')),
                ('sostav', models.TextField(verbose_name='Состав')),
                ('ves', models.IntegerField(verbose_name='Вес')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category')),
            ],
            options={
                'verbose_name_plural': 'Названия блюд и напитков',
            },
        ),
    ]
