# Generated by Django 3.1.7 on 2021-04-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ваше ФИО')),
                ('name_of_work', models.CharField(max_length=200, verbose_name='Выбранное поле деятельности')),
                ('text', models.TextField(verbose_name='Ваше резюме')),
                ('age', models.IntegerField(verbose_name='Сколько Вам лет')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Время отправки формы на сайт')),
            ],
            options={
                'verbose_name_plural': 'Форма с резюме на работу',
                'ordering': ['created', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
