# Generated by Django 3.1.7 on 2021-04-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210422_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_from',
            field=models.CharField(max_length=200, verbose_name='Время от начала бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_to',
            field=models.CharField(max_length=200, verbose_name='время до конца бронирования'),
        ),
    ]
