# Generated by Django 3.1.7 on 2021-04-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210422_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='foods',
            field=models.ManyToManyField(to='main.Food'),
        ),
    ]
