# Generated by Django 3.1.7 on 2021-05-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210426_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('text', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name_plural': 'Информация о нас',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=100, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name_plural': 'Сделать заказ',
            },
        ),
    ]
