# Generated by Django 3.1.7 on 2021-05-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210509_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/% Y/% m/% d/', verbose_name='Добавьте аватар'),
        ),
    ]
