# Generated by Django 4.2.1 on 2023-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfile",
            name="entity2",
            field=models.CharField(null=True),
        ),
    ]
