# Generated by Django 4.2.1 on 2023-05-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_csvfile_entity2"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfile",
            name="entity3",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="csvfile",
            name="entity4",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="csvfile",
            name="entity5",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="csvfile",
            name="entity6",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="csvfile",
            name="entity7",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="csvfile",
            name="entity8",
            field=models.CharField(null=True),
        ),
    ]
