# Generated by Django 4.2.1 on 2023-05-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_csvfile_entity3_csvfile_entity4_csvfile_entity5_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvfile",
            name="entity2",
        ),
        migrations.RemoveField(
            model_name="csvfile",
            name="entity3",
        ),
        migrations.RemoveField(
            model_name="csvfile",
            name="entity4",
        ),
        migrations.RemoveField(
            model_name="csvfile",
            name="entity5",
        ),
        migrations.RemoveField(
            model_name="csvfile",
            name="entity6",
        ),
        migrations.RemoveField(
            model_name="csvfile",
            name="entity7",
        ),
        migrations.RemoveField(
            model_name="csvfile",
            name="entity8",
        ),
    ]
