# Generated by Django 4.2.1 on 2023-05-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_csvfile_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfile",
            name="entity2",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="csvfile",
            name="entity3",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="csvfile",
            name="entity4",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="csvfile",
            name="entity5",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="csvfile",
            name="entity6",
            field=models.CharField(null=True),
        ),
    ]
