# Generated by Django 4.2.1 on 2023-05-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_fieldname"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FieldName",
        ),
    ]
