# Generated by Django 4.2.1 on 2023-05-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_delete_fieldname"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(null=True)),
            ],
        ),
    ]
