# Generated by Django 4.2.1 on 2023-05-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_columnscount_alter_csvfile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfile",
            name="entity7",
            field=models.CharField(null=True),
        ),
    ]
